[package]
name = "mame_data_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
reqwest = { version = "0.11", features = ["blocking"] }
indicatif = "0.16"
dialoguer = "0.9"
scraper = "0.13"
url = "2.2"
lazy_static = "1.4"